# RoadRunner Production Configuration
# AI Blockchain Analytics - High Performance PHP Server

version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php /app/psr-worker.php"
  user: "appuser"
  group: "appgroup"

# HTTP Server Configuration
http:
  address: ":8080"
  middleware: ["headers", "gzip"]
  uploads:
    forbid: [".php", ".exe", ".bat"]
  trusted_subnets:
    - "10.0.0.0/8"
    - "127.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
    - "::1/128"
    - "fc00::/7"
    - "fe80::/10"
  
  # Production pool settings
  pool:
    num_workers: 4
    max_jobs: 64
    allocate_timeout: 60s
    destroy_timeout: 60s
    supervisor:
      watch_tick: 1s
      ttl: 0s
      idle_ttl: 10s
      exec_ttl: 60s
      max_worker_memory: 512

  # SSL/TLS Configuration (for production with certificates)
  ssl:
    address: ":8443"
    redirect: true
    cert: "/etc/ssl/certs/app.crt"
    key: "/etc/ssl/private/app.key"

# Static files serving
static:
  dir: "/app/public"
  forbid: [".htaccess", ".env"]
  calculate_etag: true
  weak: false
  allow: [".txt", ".php"]
  request:
    input: "Psr\Http\Message\ServerRequestInterface"
    output: "Psr\Http\Message\ResponseInterface"

# Headers middleware
headers:
  cors:
    allowed_origin: "*"
    allowed_headers: "*"
    allowed_methods: "GET,POST,PUT,DELETE,OPTIONS"
    allow_credentials: true
    exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"
    max_age: 600
  request:
    "X-Powered-By": "RoadRunner"
    "Server": "AI-Blockchain-Analytics/2.0"
  response:
    "X-Content-Type-Options": "nosniff"
    "X-Frame-Options": "DENY"
    "X-XSS-Protection": "1; mode=block"
    "Referrer-Policy": "strict-origin-when-cross-origin"
    "Content-Security-Policy": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' wss: https:;"

# Gzip compression
gzip:
  level: 6

# Metrics and monitoring
metrics:
  address: "127.0.0.1:2112"
  collect:
    app_metric:
      type: histogram
      help: "Custom application metrics"

# Health checks
status:
  address: "127.0.0.1:2114"

# Logging
logs:
  mode: production
  level: warn
  file_logger_options:
    log_output: "/app/storage/logs/roadrunner.log"
    max_size: 10
    max_age: 30
    max_backups: 10
    compress: true

# Temporal workflow (if needed)
temporal:
  address: "127.0.0.1:7233"

# Redis configuration for RoadRunner
redis:
  addrs:
    - "redis:6379"
  master_name: ""
  username: ""
  password: ""
  db: 0
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_size: 10

# Process management
reload:
  interval: 1s
  patterns: [ ".php" ]
  services:
    http:
      recursive: true
      ignore: [ "vendor" ]
      patterns: [ ".php", ".go", ".md" ]
      dirs: [ "." ]

# Memory limits and garbage collection
limits:
  services:
    http:
      memory_limit: 512
      ttl: 0s
      idle_ttl: 10s
      exec_ttl: 60s

# Development mode (disabled in production)
# debug:
#   enabled: false