version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aegis_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ~/.composer:/tmp/composer:cached
    ports:
      - "8000:8000" # Octane
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ai_blockchain_analytics
      DB_USERNAME: postgres
      DB_PASSWORD: password
      REDIS_CLIENT: predis
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis
    command: |
      sh -c "composer install --no-interaction --prefer-dist && \
             php artisan migrate --force && \
             php artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8000"

  horizon:
    build: .
    container_name: aegis_horizon
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - redis
      - postgres
    command: php artisan horizon

  vite:
    image: node:18-alpine
    container_name: aegis_vite
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - app

  postgres:
    image: postgres:16-alpine
    container_name: aegis_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ai_blockchain_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: aegis_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  db_data:
  redis_data: 