apiVersion: v1
kind: Namespace
metadata:
  name: ai-blockchain-analytics
  labels:
    name: ai-blockchain-analytics
    environment: production
    app.kubernetes.io/name: ai-blockchain-analytics
    app.kubernetes.io/version: "1.0.0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-blockchain-analytics-quota
  namespace: ai-blockchain-analytics
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ai-blockchain-analytics-limits
  namespace: ai-blockchain-analytics
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container