name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information to help us understand your request.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: A brief description of the feature
      placeholder: "Describe the feature in one sentence"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Is your feature request related to a problem? Please describe."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "A clear and concise description of what you want to happen."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: "A clear description of any alternative solutions or features you've considered."

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Backend (Laravel)
        - Frontend (Vue.js)
        - Authentication
        - Database
        - Docker/Infrastructure
        - CI/CD
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (Blocks major functionality)
        - High (Important for user experience)
        - Medium (Nice to have)
        - Low (Minor enhancement)
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Check all that apply
      options:
        - label: This feature requires database changes
        - label: This feature requires API changes
        - label: This feature requires UI/UX changes
        - label: This feature requires documentation updates
        - label: This feature may impact performance
        - label: This feature requires testing strategy

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request