apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ai-blockchain-analytics
type: Opaque
data:
  # Base64 encoded values - update with actual credentials
  POSTGRES_USER: YWlibG9ja2NoYWluYW5hbHl0aWNz  # aiblockchainanalytics
  POSTGRES_PASSWORD: c3VwZXJzZWN1cmVwYXNzd29yZA==  # supersecurepassword  
  POSTGRES_DB: YWlfYmxvY2tjaGFpbl9hbmFseXRpY3M=  # ai_blockchain_analytics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: ai-blockchain-analytics
data:
  POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
  PGDATA: "/var/lib/postgresql/data/pgdata"