apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: ai-blockchain-analytics
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database-service
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
    protocol: TCP
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: ai-blockchain-analytics
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database-headless
spec:
  clusterIP: None
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
    protocol: TCP
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
