# RoadRunner configuration for production
version: "2.7"

# RPC configuration
rpc:
  listen: tcp://127.0.0.1:6001

# Server configuration
server:
  command: "php worker.php"
  user: "www-data"
  group: "www-data"
  env:
    - "APP_RUNTIME=RoadRunner"

# HTTP configuration
http:
  address: 0.0.0.0:8080
  max_request_size: 64MB
  middleware: ["gzip", "static"]
  uploads:
    forbid: [".php", ".exe", ".bat"]
  trusted_subnets:
    - "10.0.0.0/8"
    - "127.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
    - "::1/128"
    - "fc00::/7"
    - "fe80::/10"

  pool:
    num_workers: 4
    max_jobs: 1000
    allocate_timeout: 60s
    destroy_timeout: 60s
    supervisor:
      watch_tick: 1s
      ttl: 0s
      idle_ttl: 10s
      exec_ttl: 60s
      max_worker_memory: 512

# Static files
static:
  dir: "public"
  forbid: [".htaccess", ".env"]
  request:
    input: "request.input"
    output: "request.output"

# Metrics and health checks
metrics:
  address: 127.0.0.1:2112

# Status page
status:
  address: 127.0.0.1:2114

# Logging
logs:
  mode: production
  level: warn
  encoding: json
  output: stdout
  err_output: stderr

# Job queues (for Laravel jobs)
jobs:
  num_pollers: 2
  pipeline_size: 100000
  pool:
    num_workers: 4
    max_jobs: 100
    allocate_timeout: 60s
    destroy_timeout: 60s

  pipelines:
    default:
      driver: memory
      priority: 10
      prefetch: 10000

    crawler:
      driver: memory
      priority: 20
      prefetch: 1000

    pdf:
      driver: memory
      priority: 15
      prefetch: 500

  consume: ["default", "crawler", "pdf"]

# Redis configuration (for caching and sessions)
redis:
  addrs:
    - "${REDIS_HOST}:${REDIS_PORT}"
  username: "${REDIS_USERNAME}"
  password: "${REDIS_PASSWORD}"
  db: "${REDIS_DB}"
  master_name: ""
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s